"""Deep ownership boundaries: canonical methods and independently controlled execution."""
from typing import Protocol


class MethodRepository(Protocol):
    def candidate(self, *, method_id, title, spec, artifact, explanation, basis, key, previous=None) -> dict: ...
    def load(self, reference) -> dict: ...
    def evaluation(self, reference, receipt, *, key) -> dict: ...
    def evidence(self, reference) -> dict: ...
    def outcome(self, reference, evidence, passed, *, key) -> dict: ...
    def admit(self, reference, evidence, *, explanation, key) -> dict: ...
    def active(self, reference) -> dict: ...
    def retire(self, reference, *, explanation, basis, key) -> dict: ...
    def export(self, reference, *, destination, grants) -> dict: ...
    def receive(self, bundle, *, expected_digest, method_id, key) -> dict: ...


class MethodExecutor(Protocol):
    # Host registration owns these methods. Never resolve them from a record URI.
    def authorize(self, operation, method, facts) -> bool: ...
    def evaluate(self, method, artifact, *, case_id, facts, operation_id) -> dict: ...
    def verify_receipt(self, receipt, method) -> bool: ...
    def execute(self, method, artifact, *, request, facts, operation_id) -> dict: ...
    def quarantined(self, method) -> bool: ...
    def quarantine(self, method, *, reason) -> dict: ...
